### PR TITLE
Fix rpath on MacOS and Linux

### LINKED ISSUE #7: Does not work under MacOS
@raghavmecheri #6 

```
dlopen(/Users/raghav/Projects/[PROJECTNAME]/node_modules/@arition/torch-js/build/Release/torch-js.node, 1): Library not loaded: @rpath/libc10.dylib
      Referenced from: /Users/raghav/Projects/[PROJECTNAME]/node_modules/@arition/torch-js/build/Release/torch-js.node
      Reason: image not found
```

### PR DESCRIPTION
**Pull request by arition**
Attempt to fix rpath on MacOS and Linux.
Closes #7

### CODE REVIEW

**Comment by arition** [comment]
Seems still not work on MacOS. Not sure why ```set(CMAKE_BUILD_RPATH "@executable_path")``` does not work.

**Comment by arition** [comment]
@raghavmecheri Can you try this branch? The CI keeps running tests and I am not sure why.

**Comment by raghavmecheri** [comment]
> @raghavmecheri Can you try this branch? The CI keeps running tests and I am not sure why.

Sure -- I'll wait for this build to complete, then give it a shot

**Comment by arition** [comment]
> > @raghavmecheri Can you try this branch? The CI keeps running tests and I am not sure why.
> 
> Sure -- I'll wait for this build to complete, then give it a shot

Can you do a quick test: compile the binary files, rename the repo folder to something random, and run the tests?

**Comment by raghavmecheri** [comment]
> > > @raghavmecheri Can you try this branch? The CI keeps running tests and I am not sure why.
> > 
> > 
> > Sure -- I'll wait for this build to complete, then give it a shot
> 
> Can you do a quick test: compile the binary files, rename the repo folder to something random, and run the tests?

Tests run and all pass, both before and after renaming the repo folder 👍 

It looks like GA is lagging, can you try resetting it?

**Comment by raghavmecheri** [comment]
@arition I'm not sure why GA failed -- it looks like the tests passed

https://github.com/arition/torch-js/pull/11/checks?check_run_id=1351215484

**Comment by arition** [comment]
> @arition I'm not sure why GA failed -- it looks like the tests passed
> 
> https://github.com/arition/torch-js/pull/11/checks?check_run_id=1351215484

I think it is a CI bug. I reran a previously passed job on master, and the macos job became failed. Maybe it is safe to ignore the macos CI for now?

**Comment by raghavmecheri** [comment]
> > @arition I'm not sure why GA failed -- it looks like the tests passed
> > https://github.com/arition/torch-js/pull/11/checks?check_run_id=1351215484
> 
> I think it is a CI bug. I reran a previously passed job on master, and the macos job became failed. Maybe it is safe to ignore the macos CI for now?

It looks like jest just isn't exiting -- could you try running it with the [--forceExit](https://jestjs.io/docs/en/cli#--forceexit) flag, and see if that does anything?

**Comment by arition** [comment]
> > > @arition I'm not sure why GA failed -- it looks like the tests passed
> > > https://github.com/arition/torch-js/pull/11/checks?check_run_id=1351215484
> > 
> > 
> > I think it is a CI bug. I reran a previously passed job on master, and the macos job became failed. Maybe it is safe to ignore the macos CI for now?
> 
> It looks like jest just isn't exiting -- could you try running it with the [--forceExit](https://jestjs.io/docs/en/cli#--forceexit) flag, and see if that does anything?

The ```--forceExit``` trick works.

**Comment by raghavmecheri** [comment]
> > > > @arition I'm not sure why GA failed -- it looks like the tests passed
> > > > https://github.com/arition/torch-js/pull/11/checks?check_run_id=1351215484
> > > 
> > > 
> > > I think it is a CI bug. I reran a previously passed job on master, and the macos job became failed. Maybe it is safe to ignore the macos CI for now?
> > 
> > 
> > It looks like jest just isn't exiting -- could you try running it with the [--forceExit](https://jestjs.io/docs/en/cli#--forceexit) flag, and see if that does anything?
> 
> The `--forceExit` trick works.

cool -- could you please merge this then? I'll look into why jest isn't auto-exiting later this week.

**Pull request merged**
