### PR TITLE
WIP: Test framework

### PR DESCRIPTION
**Pull request by raghavmecheri**
@arition I think something like this would be beneficial. What do you think? If you agree, I can put some time into this over the next day or two.

### CODE REVIEW

**Comment by arition** [comment]
Yeah I think a complete test suite will be helpful to find hidden bugs. If you have any question feel free to ask me.
I suggest write unit tests using [jest](https://jestjs.io/).

**Comment by raghavmecheri** [comment]
> Yeah I think a complete test suite will be helpful to find hidden bugs. If you have any question feel free to ask me.

On a side note, have you tried contacting @kittipatv for potential access to the source repo? I think things like the ability to create issues would be beneficial in the long run

**Comment by raghavmecheri** [comment]
@arition Do you know why the `shape` key of a `toObject()` call is of type object, instead of type Array?

**Comment by arition** [comment]
> @arition Do you know why the `shape` key of a `toObject()` call is of type object, instead of type Array?

https://github.com/arition/torch-js/blob/28277f76b3769acdb0fb84a6d43d7ac59aa77af9/lib/torch.d.ts#L8

I think the ```shape``` key is always a array. Can you provide more details?

**Comment by raghavmecheri** [comment]
> > @arition Do you know why the `shape` key of a `toObject()` call is of type object, instead of type Array?
> 
> https://github.com/arition/torch-js/blob/28277f76b3769acdb0fb84a6d43d7ac59aa77af9/lib/torch.d.ts#L8
> 
> I think the `shape` key is always a array. Can you provide more details?

It was a test suite issue, sorted it out. Thanks!

**Comment by raghavmecheri** [comment]
> > @arition Do you know why the `shape` key of a `toObject()` call is of type object, instead of type Array?
> 
> https://github.com/arition/torch-js/blob/28277f76b3769acdb0fb84a6d43d7ac59aa77af9/lib/torch.d.ts#L8
> 
> I think the `shape` key is always a array. Can you provide more details?

**Comment by raghavmecheri** [comment]
@arition Do you have any idea why that one ubuntu build is failing? I haven't tried building on ubuntu, it seems to work just fine locally. Is the build just not linking to the CUDA libraries correctly?

**Comment by arition** [comment]
@raghavmecheri The CI does not have a complete GPU environment, so it is impossible to run pyTorch linked with CUDA. I have removed the cuda-test job. Can you merge the change and I can start to review your pr?

**Comment by raghavmecheri** [comment]
> @raghavmecheri The CI does not have a complete GPU environment, so it is impossible to run pyTorch linked with CUDA. I have removed the cuda-test job. Can you merge the change and I can start to review your pr?

Done :)

**Review by arition — CHANGES_REQUESTED** [review]
Can you replace the tabs in ```tests/rand.test.js``` and ```tests/tensor.test.js``` into two spaces? I also suggest add a eslint rule or prettier config to force the use of two spaces.

**Comment by raghavmecheri** [comment]
> Can you replace the tabs in `tests/rand.test.js` and `tests/tensor.test.js` into two spaces? I also suggest add a eslint rule or prettier config to force the use of two spaces.

Done + added eslint rule

**Review by arition — APPROVED** [review]

**Comment by arition** [comment]
Thanks! All changes are merged.

**Pull request merged**
